image: archlinux
sources:
  - https://github.com/mklein994/dynamic_wallpaper
environment:
  PROJECT_PATH: "dynamic_wallpaper"
tasks:
  - rustup: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
        sh -s -- -y --profile minimal --component rustfmt
      cat ~/.cargo/env >> ~/.buildenv
  - setup_check: |
      rustc --version
      cargo --version
  - fmt_check: |
      cd $PROJECT_PATH
      cargo fmt -- --check
  - build: |
      cd $PROJECT_PATH
      cargo build --verbose
  - test: |
      cd $PROJECT_PATH
      cargo test --verbose
