language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
notifications:
  email: false
