on: push

name: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    continue-on-error: ${{ matrix.rust != 'stable' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: build
        run: cargo build

      - name: test
        run: cargo test

      - name: rustfmt
        run: cargo fmt --all --check

      - name: clippy
        run: cargo clippy -- -D warnings
